import React from 'react';
import {
  Loader2,
  ChevronRight,
  ShoppingBag,
  Minus,
  Plus,
  Trash2,
  Menu,
  X,
  ChevronLeft,
  Search,
  CheckCircle2,
  Clock,
  Utensils,
  QrCode,
  BarChart3,
  LogOut,
  Settings,
  User,
  Star,
  PlayCircle,
  Mail,
  Check,
  Save,
  Edit3,
  Send,
  Power,
  ExternalLink,
  Instagram,
  Twitter,
  Facebook,
  ArrowRight,
  Lock,
  ChefHat,
  ClipboardList,
  TrendingUp,
  Users,
  PieChart,
  PlusCircle,
  Image
} from 'lucide-react';

export const Icons = {
  Spinner: Loader2,
  Right: ChevronRight,
  Left: ChevronLeft,
  Bag: ShoppingBag,
  Minus: Minus,
  Plus: Plus,
  Trash: Trash2,
  Menu: Menu,
  Close: X,
  Search: Search,
  Success: CheckCircle2,
  Clock: Clock,
  Utensils: Utensils,
  Qr: QrCode,
  BarChart: BarChart3,
  Logout: LogOut,
  LogOut: LogOut,
  Settings: Settings,
  User: User,
  Star: Star,
  PlayCircle: PlayCircle,
  Mail: Mail,
  Check: Check,
  Save: Save,
  Edit: Edit3,
  Send: Send,
  Power: Power,
  ExternalLink: ExternalLink,
  Instagram: Instagram,
  Twitter: Twitter,
  Facebook: Facebook,
  ArrowRight: ArrowRight,
  X: X,
  Lock: Lock,
  Chef: ChefHat,
  List: ClipboardList,
  TrendingUp: TrendingUp,
  Users: Users,
  PieChart: PieChart,
  PlusCircle: PlusCircle,
  Image: Image
};
